name: run_tests_net5.0

on:
  push:
    branches: [ main ]
    paths:
      - 'src/net5.0/**.*'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/net5.0/**.*'

defaults:
  run:
    working-directory: ./src/net5.0

jobs:
  test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: restore dependencies
      run: dotnet restore
    - name: build
      run: dotnet build --no-restore
    - name: test
      run: dotnet test --no-build --verbosity normal
