name: optimizely cms 11

on:
  push:
    branches: [ main ]
    paths:
      - 'src/net48/**.*'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/net48/**.*'

defaults:
  run:
    working-directory: ./src/net48

env:
  CONFIGURATION: Release

jobs:
  test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: setup vstest path
      uses: darenm/Setup-VSTest@v1

    - name: restore dependencies
      run: nuget restore

    - name: build for cms 11
      run: msbuild /property:Configuration=${{env.CONFIGURATION}}

    - name: test with latest CMS version
      run: vstest.console.exe Lorem.Testing.Optimizely.CMS.Test\bin\${{env.CONFIGURATION}}\net48\Lorem.Testing.Optimizely.CMS.Test.dll /TestCaseFilter:"verification=required" /TestAdapterPath:Lorem.Testing.Optimizely.CMS.Test\bin\${{env.CONFIGURATION}}\net48\

    - name: test with minimum CMS version
      run: vstest.console.exe Lorem.Testing.Optimizely.CMS.Test.Min\bin\${{env.CONFIGURATION}}\net471\Lorem.Testing.Optimizely.CMS.Test.Min.dll /TestCaseFilter:"verification=required" /TestAdapterPath:Lorem.Testing.Optimizely.CMS.Test.Min\bin\${{env.CONFIGURATION}}\net471\